# Generated by Django 4.0.1 on 2022-01-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_class_learner_class_subject_learner_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='Class',
        ),
        migrations.AddField(
            model_name='class',
            name='learner',
            field=models.ManyToManyField(blank=True, to='users.Learner'),
        ),
    ]
